# Generated by Django 5.2.3 on 2025-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
